In [2]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv('imdb_top_1000.csv')

In [5]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [40]:
df1 = df.drop(['Runtime','Released_Year','Certificate','Meta_score','No_of_Votes','IMDB_Rating','Gross'],axis=1)

In [29]:
df1.head()

,Poster_Link,Series_Title,Genre,Overview,Director,Star1,Star2,Star3,Star4,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,Drama,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,"Crime, Drama",An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,"Crime, Drama",The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,"Crime, Drama",A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"

In [22]:
df1['Gross'].describe()

count           831
unique          823
top       4,360,000
freq              5
Name: Gross, dtype: object

In [23]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Series_Title  1000 non-null   str
 1   Genre         1000 non-null   str
 2   IMDB_Rating   1000 non-null   float64
 3   Gross         831 non-null    str
dtypes: float64(1), str(3)
memory usage: 73.0 KB

In [42]:
df1.isnull().sum()

Poster_Link     0
Series_Title    0
Genre           0
Overview        0
Director        0
Star1           0
Star2           0
Star3           0
Star4           0
dtype: int64

In [41]:
df1.shape

(1000, 9)

In [52]:
df1["tags"] = ( df1['Series_Title'] + ' ' + df1['Genre'] + ' ' + df1['Director'] + ' ' + df1['Star1'] + ' ' + df1['Star2'] + ' ' + df1['Star3'] + ' ' + df1['Star4'] )

In [53]:
df1.head()

,Poster_Link,Series_Title,Genre,Overview,Director,Star1,Star2,Star3,Star4,tags
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,Drama,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,The Shawshank Redemption Drama Frank Darabont ...
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,"Crime, Drama",An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"The Godfather Crime, Drama Francis Ford Coppol..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"The Dark Knight Action, Crime, Drama Christoph..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,"Crime, Drama",The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"The Godfather: Part II Crime, Drama Francis Fo..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,"Crime, Drama",A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"12 Angry Men Crime, Drama Sidney Lumet Henry F..."

In [54]:
df1['tags'][0]

'The Shawshank Redemption Drama Frank Darabont Tim Robbins Morgan Freeman Bob Gunton William Sadler'

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [61]:
vectorizedText = TfidfVectorizer(stop_words='english',max_features=5000)

In [63]:
finalVectors = vectorizedText.fit_transform(df1['tags'])

In [64]:
finalVectors

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13982 stored elements and shape (1000, 5000)>

In [65]:
df1.shape

(1000, 10)

In [66]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Poster_Link   1000 non-null   str
 1   Series_Title  1000 non-null   str
 2   Genre         1000 non-null   str
 3   Overview      1000 non-null   str
 4   Director      1000 non-null   str
 5   Star1         1000 non-null   str
 6   Star2         1000 non-null   str
 7   Star3         1000 non-null   str
 8   Star4         1000 non-null   str
 9   tags          1000 non-null   str
dtypes: str(10)
memory usage: 557.6 KB

In [67]:
df1.head()

,Poster_Link,Series_Title,Genre,Overview,Director,Star1,Star2,Star3,Star4,tags
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,Drama,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,The Shawshank Redemption Drama Frank Darabont ...
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,"Crime, Drama",An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"The Godfather Crime, Drama Francis Ford Coppol..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"The Dark Knight Action, Crime, Drama Christoph..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,"Crime, Drama",The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"The Godfather: Part II Crime, Drama Francis Fo..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,"Crime, Drama",A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"12 Angry Men Crime, Drama Sidney Lumet Henry F..."

In [69]:
from sklearn.neighbors import NearestNeighbors

In [72]:
Knn = NearestNeighbors(n_neighbors=6,metric='cosine')
Knn.fit(finalVectors)

NearestNeighbors(metric='cosine', n_neighbors=6)

In [104]:
def recomend(movie):
    indexes = df1[df1['Series_Title'] == movie].index[0]

    distance, indices = Knn.kneighbors(finalVectors[indexes])

    
    for i in indices[0][1:]:
        print(df1.iloc[i]['Series_Title'])

recomend('The Dark Knight')

The Dark Knight Rises
The Prestige
Batman Begins
Brokeback Mountain
3:10 to Yuma

In [79]:
import matplotlib.pyplot as plt

In [105]:
import pickle

In [109]:
pickle.dump(df1, open('movies.pkl', 'wb'))

In [ ]:
pickle.dump(Knn,open('Model.pkl'))

In [111]:
pickle.dump(finalVectors, open('finalVectors.pkl', 'wb'))